### ISSUE TITLE
Can I play multiples parts at the same time?

### ISSUE THREAD

**Issue by r-zander** [processing/p5.js-sound#125]
I'd like to create a project with multiple instruments playing at various tatums. My first idea was to create 1 p5.Part per tatums. 
As it turns out, playing multiple parts at the same time leads to some unexpected behavior where the second part changes the tatums of the first part, while the second part is rarely ever ticked.

I wrote a little test to confirm this suspicion: http://rza.io/sandbox/partsTest/
On the left side a part with 1/4 tatums is started on setup (with about 900ms between each tick). As soon as you click on right side, a part with 1/8 tatums is created & started - and the 1/4 part is executed every ~450ms, while the 1/8 part is rarely (or never) ticked.

Now my question is: Is this an expected behavior? Am I using Parts & Phrases wrong? Can I only play 1 part at a time?

**Comment by CosmicChild** [comment]
Kind of same problem here. Only one part works at a time and I get some random behavior.

**Comment by b2renger** [comment]
@r-zander @CosmicChild 

I think "parts" are big chunk of music (like chorus, verse) - if you plan to play simultaneously what you want is probably to have one part and several phrases ?

The case in which you would want several parts synched is if you several time signatures playing at the same time :  let's say one part expressed in 3/4 and one in 9/5 (just to be wild)

From your code it seems that you only want a division of the bpm.

First in your code , you do : 
```javascript
fourthsPart = new p5.Part(0, 1 / 4);
```
I'm not sure you can actually do that - I mean create a part with no steps, as the first argument is the number of steps.

And from this reference : http://p5js.org/reference/#/p5.Part

You could probably just do it like this : 

```javascript
var  myPart;
var eightsPhrase, fourthsPhrase
var eigthts = [1,1,1,1];
var fourths = [1,0,1,0];

function setup() {

  eightsPhrase = new p5.Phrase('eights', playE, eights);
  fourthsPhrase = new p5.Phrase('drum', playF, fourths);
  myPart = new p5.Part(4,1/8);
  myPart.addPhrase(fourthsPhrase);
  myPart.setBPM(60);
}

function draw() {
  background(0);
}

function mouseClicked(){
   myPart.addPhrase(eightsPhrase);
}

function playE(){

}

function playF(){

}

```
would that work ? it's also worth using **removePhrase()** or **replaceSequence()**

**Comment by CosmicChild** [comment]
I guess that would work for phrases with different tatums.
The problem, at least on my side, is that I want to use different BPMs, that have no integer relation between them. So, to go with this approach I would have to make really small subdivisions, which does not seem too good of an idea.....

**Comment by b2renger** [comment]
@CosmicChild 

What is it exactly that you want to achieve ? do you have a small and simple example we can work on ?

Working with small subdivision might work in some cases, if you just want to prototype it might be ok, be on some other scale it might be a total disaster.

Btw I found the doc to the Score object : http://p5js.org/reference/#/p5.Score
it's made to contain parts, maybe it would help ?

**Comment by CosmicChild** [comment]
Actually I'm trying to build a music creation platform, for other users. So it needs to be solid, I cannot risk having a disaster.....
Basically I have 8 simultaneous musical objects and they all have completely independent tempi. They all need to play at the same time at different speeds (that may be changed by the user).
I have checked the score object but it also works in a sequence, activating one part at a time, so it doesn't solve the problem :(

Ultimately, what I need is any object that can trigger a function every X miliseconds. It doesn't have to be the sound object, I can create the step sequencer myself. But I cannot control this iteration from the draw() because it is too slow (max 60 fps, I can't actually go over 20fps with this sketch). I would need some other function that can work and count time outside of draw().

**Comment by b2renger** [comment]
hum I see ... I'm sorry because I don't really know this part of the code but think this use case might be out of the scope of p5.sound, which is wrapper to simplify the use of the Waa to beginners in code. 

Those objects are wrapped around other objects from Tone.js : https://tonejs.github.io

You could also have a look to this article which is a reference when it comes to scheduling. I'll do some tests with the current implementation.

**Comment by CosmicChild** [comment]
Thanks, I will check it out

**Comment by CosmicChild** [comment]
I find a solution, using multiple Metro() objects.
The p5.Metro is not listed in the p5.Sound reference, but it exists and it is used to construct the Part objects.
Calling multiple Metro()s produces the same result as multiple Part()s, that is only one playing and some random notes poping out from time to time. However, a really simple edit of the sound library permits to replicate the Metro() object, creating for exaple MetroA(), MetroB(), MetroC(), etc. All of them with the exact same composition, but in this way they get an independent Clock. Then we can call from our sketch:

myMetro1 = new p5.MetroA(callback1);
myMetro2 = new p5.MetroA(callback1);

myMetro1.setBPM(60);
myMetro2.setBPM(61);
myMetro1.setLength(0.25);
myMetro2.setLength(0.25);
myMetro1.start();
myMetro2.start();


Since the Metro object is created to work with Parts and Phrases, and calls back the function that is set in the Phrase object, we need to modify our MetroA object to include this callback.

**Comment by b2renger** [comment]
Great ! I saw the metro object and thought the solution would be tied to it.

@CosmicChild could you share your edit ? 

@therewasaguy do you think we should expose the p5.Metro object in the doc ?

**Comment by therewasaguy** [comment]
Sorry for my delay chiming in here, thank you @r-zander for the excellent test and thanks @CosmicChild  and @b2renger for your insights.

Multiple parts should be able to play at the same time and with separate BPM's.

@CosmicChild I'm curious to check out your edit, if you think it'd be useful feel free to send a PR.

In the meantime I have a fix here: https://github.com/processing/p5.js-sound/commit/069c84c7fbacd2b25c0084265daf624cf32c2029 Let me know if this does the trick, and if you have suggestions or improvements. The problem was that all Metros were referring to the same `prevTick`, rather than each instance keeping track of its own `prevTick`, which they use to determine whether it's time to fire their part / phrase callbacks.

Exposing the Metro in the docs is a great idea @b2renger. I think what we need is a simple way to create a loop that fires a callback at a tempo, something like @CosmicChild's example. That's very flexible and powerful, and I think that's how most people wind up using the p5.Part anyway (via the `onStep` method). I would really like to sit down and improve Part/Phrase/Score based on a meeting with Andrew R Brown who inspired these classes, but making it easy to do just this was one of his suggestions. At the moment the Metro is a bit too tied into the Part/Phrase system, maybe it's worth abstracting that so that Metro can function independently, or creating a different class to handle loops. I'll create a separate issue for this...

**Comment by CosmicChild** [comment]
I hadn't realized the problem was the prevTick, so I just created multiple metro functions, naming them metroA, metroB, metroC, etc. They are all exactly the same exept for the name. Of course, this was a specific solution for my problem, but it wouldn't work for the sound library in general.*
I also changed the callback to a function that can be called from the sketch, I think it was more direct this way.

Here is my edit:

```
var metroA;
metroA = function () {
  'use strict';
  var p5sound = master;
  // requires the Tone.js library's Clock (MIT license, Yotam Mann)
  // https://github.com/TONEnoTONE/Tone.js/
  var Clock = Tone_core_Clock;
  var ac = p5sound.audiocontext;
  // var upTick = false;
  p5.MetroA = function (callback) {
    this.callback = callback;
    this.clock = new Clock({ 'callback': this.ontick.bind(this) });
    this.syncedParts = [];
    this.bpm = 120;
    // gets overridden by p5.Part
    this._init();

  };
  var prevTick = 0;
  var tatumTime = 0;
  p5.MetroA.prototype.ontick = function (tickTime) {
    var elapsedTime = tickTime - prevTick;
    var secondsFromNow = tickTime - p5sound.audiocontext.currentTime;
    if (elapsedTime - tatumTime <= -0.02) {
      return;
    } else {
      this.callback(secondsFromNow);
      prevTick = tickTime;
      this.metroATicks += 1;
    }
  };
  p5.MetroA.prototype.setBPM = function (bpm, rampTime) {
    var beatTime = 60 / (bpm * this.tatums);
    var now = p5sound.audiocontext.currentTime;
    tatumTime = beatTime;
    var rampTime = rampTime || 0;
    this.clock.frequency.setValueAtTime(this.clock.frequency.value, now);
    this.clock.frequency.linearRampToValueAtTime(bpm, now + rampTime);
    this.bpm = bpm;
  };
  p5.MetroA.prototype.getBPM = function (tempo) {
    return this.clock.getRate() / this.tatums * 60;
  };
  p5.MetroA.prototype._init = function () {
    this.metroATicks = 0;
  };
  // clear existing synced parts, add only this one
  p5.MetroA.prototype.resetSync = function (part) {
    this.syncedParts = [part];
  };
  // push a new synced part to the array
  p5.MetroA.prototype.pushSync = function (part) {
    this.syncedParts.push(part);
  };
  p5.MetroA.prototype.start = function (timeFromNow) {
    var t = timeFromNow || 0;
    var now = p5sound.audiocontext.currentTime;
    this.clock.start(now + t);
    this.setBPM(this.bpm);
  };
  p5.MetroA.prototype.stop = function (timeFromNow) {
    var t = timeFromNow || 0;
    var now = p5sound.audiocontext.currentTime;
    this.clock.stop(now + t);

  };
  p5.MetroA.prototype.beatLength = function (tatums) {
    this.tatums = 1 / tatums / 4;
  };
}(master, Tone_core_Clock);
```
