### ISSUE TITLE
Playback rate in Chrome

### ISSUE THREAD

**Issue by 8ude** [processing/p5.js-sound#135]
The chrome browser doesn't seem to be registering changes in playback rate - that is, everything plays back at normal speed.

Specifically noticed this when looking at phrases = https://p5js.org/reference/#/p5.Phrase

**Comment by ericrosenbaum** [comment]
I've noticed this bug as well. it was affecting the [MK-1](https://ericrosenbaum.github.io/MK-1/) and I fixed it with this [commit](https://github.com/ericrosenbaum/MK-1/commit/7b5c727b582c89e4aa842d195621347c45322796) which included a couple of small changes to my own code and to the p5 sound library (marked with "ericr" in comments). I never exactly figured out what was happening, but it felt like a "race condition" situation in my case: the sounds were playing back sometimes at the correct shifted rate, and sometimes at normal speed. One thing I changed in p5.sound.js was:

`this.bufferSourceNode.playbackRate.linearRampToValueAtTime(Math.abs(rate), now);`

to

`this.bufferSourceNode.playbackRate.value = Math.abs(rate);`

**Comment by ericrosenbaum** [comment]
quite possibly this is the same issue being discussed on tonejs:

https://github.com/Tonejs/Tone.js/issues/163

**Comment by therewasaguy** [comment]
Thank you, @ericrosenbaum, and thanks for the bug report + test case, @8ude! I'm sorry for my slow response.

Seems like we have some scheduling bugs... If I run the p5.phrase example on its own, outside of the p5 reference page, it works, but inside of the page, the audiocontext scheduling is less predictable. If I remove `time` from the call to `play`, it works. But in both settings, this technique that had worked previously does not work any more:  `mySound.play(time, playbackRate);`

@ericrosenbaum your solution of assigning the value directly instead of scheduling it looks similar to @tambien's solution for Tone.js. I'm pretty sure I've run into a bug where, once you start using the web audio api scheduler (i.e. `linearRampToValueAtTime(val, time)`), then `value =` is ignored. I'm trying to remember which browsers had that issue, and I'm wondering if that's still an issue.

**Comment by therewasaguy** [comment]
Ok, `value = ` seems to do the trick when initializing a BufferSourceNode. Then, when changing the playback rate, I am continuing to use `linearRampToValueAtTime` instead of `setValueAtTime` because setValueAtTime doesn't work in Chrome, and p5.sound doesn't have the ability to schedule ramp playback changes. This would be a nice feature to add, though!
