### ISSUE TITLE
p5.SoundFile example broken on Chromium

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js-sound#181]
https://p5js.org/reference/#/p5.SoundFile

Sketch stuck on 'Loading...' 

Chromium 57.0.2987.133 on OSX 10.10

```

p5.sound.min.js:3 AudioContext error at decodeAudioData for assets/doorbell.mp3
 The error stack trace includes: 
decodeAudioData
(anonymous) @ p5.sound.min.js:3

/reference/#/p5.SoundFile:1 Uncaught (in promise) DOMException: Unable to decode audio data
```

(likely to do with chromium's poor support for .mp3)

![screen shot 2017-06-16 at 7 06 02 pm](https://user-images.githubusercontent.com/737638/27224283-dfa716b0-52c6-11e7-9ed0-6a362fd2fb7c.png)

**Comment by therewasaguy** [comment]
> likely to do with chromium's poor support for .mp3

This is the issue. There is already Chromium compatible `ogg` file with the same name in the assets directory. So to fix this, we could add this to the example

```
  soundFormats('mp3', 'ogg');
```

Or pass an array into loadSound like this

```
loadSound( ['assets/doorbell.mp3', 'assets/doorbell.ogg'] );
```

I'm not sure if this is worth doing, since it complicates what is supposed to be a simple example, and the second solution is mentioned in the documentation on [this page](If you want to ensure compatability, instead of a single file path, you may include an Array of filepaths, and the browser will choose a format that works.). What do you think?
