### ISSUE TITLE
Google Summer of Code 2018 - Algorithmic Composition with p5.Sound

### ISSUE THREAD

**Issue by JunShern** [processing/p5.js-sound#259]
Hi @therewasaguy !

I was excited to see your project "Algorithmic Composition with p5.Sound" on the [project lists page](https://github.com/processing/processing/wiki/Project-List) for Processing Foundation's Google Summer of Code, I would love to take on this project!

One of the desired outcomes for the project:

> A collection of examples that can be used by educators and people with an interest in music + code

I'm keen to get started on this right away to show my engagement, and was wondering if there is a "wishlist" of examples for p5.js-sound or shall I just start with any popular algorithmic composition algorithm?

For example, I'm happy to start with an example of [Markov-generated music](https://en.wikipedia.org/wiki/Markov_chain#Music). Let me know!

**Comment by therewasaguy** [comment]
Hi @JunShern, thanks for reaching out!

Markov music would definitely be on the wishlist. I think that's a great place to start as a developer. maybe as part of an experimentation/prototyping/research phase. It could help give you ideas for how to approach the project, i.e. how to structure the examples and how to support them with improvements to the library.

I want to highlight this bit from the Processing GSoC page:

> For all of our projects, it's incredibly important that things are kept as simple and user-friendly as possible. Our work is not for developers, it's for people who are less familiar with code, and/or just want to get things done. We're far less interested in features to make the environments more powerful for advanced users than we are in features that make it easier to handle tasks that are common for a wide range of our audience.

So I'd start thinking about how to distill each example to something that is simple and user-friendly. What concepts might help build up to the Markov chain example? Should these have their own examples? Something on randomness? Pitch? Melody? Objects and Arrays? We already have some examples that live in the [p5 website repo](https://github.com/processing/p5.js-website/tree/master/src/data/examples/en) and appear at https://p5js.org/examples/. There might be some concepts that only have a visual example which could also be applied to sound. We also have some (less visible) examples that live in the p5 sound repo's `/examples` directory.

As you dig in, I'd also look for ways to improve the library so that it can better support algorithmic composition. This could feed into the other expected outcomes of this project, which are:

> - Improved documentation for the features utilized by these examples
> - Refinements to the p5.sound library that make such examples possible

I imagine any algorithmic composition project will want to build off the work of @jvntf from last GSoC, including the [p5.SoundLoop](https://p5js.org/reference/#/p5.SoundLoop/start) (a draw loop for sound) and [Synth classes](https://p5js.org/reference/#/p5.PolySynth) (which @b2renger kicked off). Using and improving documentation for these classes might also be a good place to start diving in as a contributor—the reference pages are generated from [inline documentation](https://github.com/processing/p5.js/wiki/Inline-documentation).

One last thing to add—think about where collaborations can happen as part of this project. For example, we might be able to utilize (and contribute to) [p5.func](https://idmnyu.github.io/p5.js-func/) rather than write our own function generators, and an example with [ml5js](https://github.com/ml5js/ml5-library) would be very cool.

**Comment by b2renger** [comment]
@JunShern @therewasaguy 

Great I'd love to see this project kicked off. Don't hesitate to ping us about your work.

It could be very nice to look up the work of Tero Parviainen (@teropta) and adapt some of the principles he explains in his awesome slideshows with p5js code (as simple as possible as Jason points out)

**Comment by JunShern** [comment]
Awesome, thanks so much for the great feedback and cool ideas! I'm fleshing out a few more ideas right now but before I get into those other details, I was wondering if I could get some input on my other question about MIDI in p5.js (https://github.com/processing/p5.js-sound/issues/258). The way I see it, p5.js-sound could stand to gain so much from MIDI support, and it opens up a whole world of other possibilities. 

This directly relates to the project since machine composition deals most naturally with MIDI notes. And though we already have support for MIDI note synthesis with oscillators, I believe that users will get much more excitement out of being able to use real instrument sounds by use of soundfonts (not to mention that many digital musicians work in MIDI so further implementation of MIDI input/output would place p5.js comfortably into their workflow).

@therewasaguy

**Comment by JunShern** [comment]
@therewasaguy , regarding the p5.SoundLoop and SynthClasses you mentioned. I would be happy to work on documentation for this as part of my first exploration, but I have actually not figure out how to get them working as it is:

1. p5.SoundLoop - [the example on the p5.js website](https://p5js.org/reference/#/p5.SoundLoop) does not produce any sounds when I click on the box. @jvntf 

2. PolySynth - When pasted into a p5 environment and executed, the [example code](https://p5js.org/reference/#/p5.PolySynth) does nothing but produce crackling noises for me. A quick glance at the developer console shows some deprecation warnings (on Google Chrome Version 65.0.3325.146 on Linux) but I don't know if this is the reason for the noises. @b2renger 

I might just be using them incorrectly since the available information on them is indeed sparse, but if they turn out to be bugs then I will open new issues for each and look into them further. Is there information online somewhere about these new features? If they were previous GSoC projects I assume there might be documentation/reports I can use to find out more.

**Comment by therewasaguy** [comment]
> p5.SoundLoop - the example on the p5.js website does not produce any sounds when I click on the box. @jvntf

The sound loop is not meant to be interactive, it triggers a sample every interval (2 seconds in this case) and stops after it reaches maxIterations.

The MonoSynth example has a reference to `loadPreset` that needs to be removed [here](https://github.com/processing/p5.js-sound/blob/master/src/monosynth.js#L22). That's a quick easy PR for anyone who wants to do it!

The PolySynth example should be updated, yikes. It has a lot of low frequencies overlapping leading to crackling sounds on computer speakers (was this meant to use `midiToFreq`, @jvntf?) and it schedules them all at the same time (0 seconds from now) according to the [`play` method](https://p5js.org/reference/#/p5.PolySynth/play).

One other issue with both MonoSynth and PolySynth is that their dispose method throws an error. Making an issue for this here https://github.com/processing/p5.js-sound/issues/261

The deprecation warnings are ok, referenced here https://github.com/processing/p5.js-sound/issues/255

**Comment by jvntf** [comment]
hey all! 
re: polysynth example yes PolySynth is scheduling those example values as frequency not MIDI. Seems like the documentation is incorrect. If I remember correctly, the [AudioVoice](https://github.com/processing/p5.js-sound/blob/master/src/audioVoice.js) architecture allows PolySynth to set notes by string ("A4", "C#3" etc...) or by frequency value. I think we decided this was the most straightforward (@therewasaguy ?), but of course this is up for debate! 

Here is an issue for PolySynth docs to be updated to accept `note` as frequency for midi string rather than midi value.
@JunShern if you change the example values to something more audible you will here something from the example!

**Comment by JunShern** [comment]
Thanks for spotting that, @jvntf! 

I would point out that this "C3" type note representation is different from what we currently have on monosynth, which uses MIDI note numbers. I'm sure we want to standardise the note representation throughout the classes, would be interested to know what the decision was last time and how we should move forward. @therewasaguy

**Comment by JunShern** [comment]
Thanks for pointing that out, @jvntf! Continued in #266.
