### ISSUE TITLE
PolySynth docs incorrect

### ISSUE THREAD

**Issue by jvntf** [processing/p5.js-sound#266]
The documentation and inline example indicate that the `note` param should be specified as a MIDI value. This does is not correct-- as it stands, note should be specified as a midi note string or as a frequency. polysynth.play() calls polysynth.noteAttack() which calls [audiovoice._setNote()](https://github.com/processing/p5.js-sound/blob/master/src/audioVoice.js#L27)

**Comment by JunShern** [comment]
Hi @jvntf, I was just having a look at this, I tried changing the example but got confused by some errors, possibly a bug.

To begin with, this doesn't work:

```javascript
var polysynth;
function setup() {
  polysynth = new p5.PolySynth();
  var velocity = 0.7;
  var time = 0;
  polysynth.play("C3",velocity,time,1.5);
  polysynth.play("E3",velocity,time+=0.5,1.0);
  polysynth.play("G3",velocity,time+=0.5,0.5);
  time += 1.0; // Rest
  polysynth.play("G3",velocity,time+=0.5,1.5);
  polysynth.play("E3",velocity,time+=0.5,1.0);
  polysynth.play("C3",velocity,time+=0.5,0.5);
}
```

which gives the error: `Uncaught TypeError: Cannot read property 'triggerAttack' of undefined (sketch: line 11)`.

But when I just change the duration parameter of the first few notes, then it works:

```javascript
var polysynth;
function setup() {
  polysynth = new p5.PolySynth();
  var velocity = 0.7;
  var time = 0;
  polysynth.play("C3",velocity,time,1.0);
  polysynth.play("E3",velocity,time+=0.5,0.5);
  polysynth.play("G3",velocity,time+=0.5,1.0);
  time += 1.0; // Rest
  polysynth.play("G3",velocity,time+=0.5,1.5);
  polysynth.play("E3",velocity,time+=0.5,1.0);
  polysynth.play("C3",velocity,time+=0.5,0.5);
}
```

I'm wondering if this might have something to do with having a limited number of polyphonic voices available, maybe? I could look into it some more but hopefully someone more familiar with it can pick out the problem quickly.

**Comment by JunShern** [comment]
Also to clear this up, both our MonoSynth and PolySynth classes accept the same inputs: either a note string "A#3", or frequency in Hz. If a user wants to work with MIDI numbers, they need to first convert using midiToFreq().

The following example illustrates the three possibilities:

```javascript
var synth;
function setup() {
  synth = new p5.MonoSynth(); // Same for PolySynth
  var time = 0;
  synth.play("C4",1,time+=0.5,0.5);
  time += 1;
  synth.play(261,1,time+=0.5,0.5);
  time += 1;
  synth.play(midiToFreq(60),1,time+=0.5,0.5);
}
```

According to [this](https://newt.phys.unsw.edu.au/jw/notes.html), the three representations should be equivalent. However if you run the sketch, you'll hear that the "C4" sound is one octave higher than the other two (it happens in both MonoSynth and PolySynth) - I believe this is a bug caused by simply having the octave number one octave off?

**Comment by jvntf** [comment]
i think your problem may be time based. when you just schedule values inside of `setup()`, you are using the raw javascript clock which is not accurate. I am guessing that the problem you are running seeing some semi-random behavior in which sometimes the PolySynth is instantiated and voices are allocated in the correct order and notes are scheduled at the correct time, and sometimes it does not work. I recommend trying to work inside of a `p5.SoundLoop` to avoid this. 

> Also to clear this up, both our MonoSynth and PolySynth classes accept the same inputs
yes! MonoSynth is just a wrapper for AudioVoice, and PolySynth sort of bundles AudioVoices together, so API should be common. I think we should actually get rid of the string notation for a note ("C3") because it is clunky and potentially confusing because AudioVoice stores the data as a frequency anyway. what do you think @JunShern ? and @b2renger @therewasaguy

**Comment by JunShern** [comment]
Hey @jvntf ! Thanks for the reply. Regarding the notation, string notation _is_ rather clunky, but from an educator's point of view I think there is still value in having that option. It makes it easy to introduce the concept of playing notes in notation that people already understand, and then I expect that users will start using the MIDI-number representation more often once they become more comfortable. It's a nice-to-have at little extra cost!

About timing for PolySynth, I'm still having some troubles: Following your advice, I began working within a SoundLoop by building off @therewasaguy's [example](http://alpha.editor.p5js.org/talkscheap/sketches/SydY4pKKM) from [another thread](https://github.com/processing/p5.js-sound/issues/258#issuecomment-373862322):

```javascript
function setup() {
  var synth = new p5.MonoSynth();
  var pitches = [64, 66, 71, 73, 74, 66, 64, 73, 71, 66, 74, 73].map(midiToFreq)
  var durations = [0.25, 0.5, 0.33];
  var i = 0;

  var looper = new p5.SoundLoop(function(timeFromNow) {
    // set the next interval to a random duration
    var interval = durations[floor(random() * 3)];

    // change the interval until the next sound loop
    looper.interval = interval;

    // play a note
    var pitch = pitches[i % pitches.length];
    var velocity = random(0.5, 1.0);
    var decay = interval;
    synth.play(pitch, timeFromNow, velocity, decay)
    i++;
  });
  
  looper.start();
}
```

Which works fine. So I tried changing from MonoSynth to PolySynth, and it still works fine (but there are now overlaps between the notes! I'll come back to this).

Next, instead of reading choosing `pitches` in a circular order, I use `random(pitches)`:

```javascript
function setup() {
  var synth = new p5.PolySynth();
  var pitches = [64, 66, 71, 73, 74, 66, 64, 73, 71, 66, 74, 73].map(midiToFreq)
  var durations = [0.25, 0.5, 0.33];
  var i = 0;
  
  var looper = new p5.SoundLoop(function(timeFromNow) {
    // set the next interval to a random duration
    var interval = durations[floor(random() * 3)];

    // change the interval until the next sound loop
    looper.interval = interval;

    // play a note
    var pitch = random(pitches); //pitches[i % pitches.length];
    var velocity = random(0.5, 1.0);
    var decay = interval;
    synth.play(pitch, timeFromNow, velocity, decay);
    i++;
  });
  
  looper.start();
}
```

Which doesn't seem like it should be troublesome, but the same `Uncaught TypeError: Cannot read property 'triggerAttack' of undefined` problem comes up. 

From what I can see, I'm guessing that by setting `looper.interval = interval` and `decay = interval`, @therewasaguy intended to have each note play monophonically, each note playing only for the duration of its own loop iteration. But on changing to PolySynth, it becomes clear that multiple notes do sound simultaneously, meaning that this usage of the interval is not actually correct.

Is this intended behaviour, and if so, can you please give an example of how the SoundLoop and PolySynth classes are intended to be used together? I haven't been able to come up with an example which works to my liking yet, unfortunately.

**Comment by therewasaguy** [comment]
took a look at this earlier with @JunShern. We found that `currentVoice` was sometimes being set to NaN and [here](https://github.com/therewasaguy/p5.js-sound/commit/1a07a823e588c54de5ae40d34aa5e90aa558c59f#diff-6ea69ac91be7c3704f029182382c35b8R206) is one possible fix for that.

I think we're also releasing notes early, and started to dig into this, but the voice handling with a Tone Timeline Signal is pretty complex.

I'm also wondering if it might just make sense to remove that complexity and instead we could iterate through the array of `this.audiovoices`, keeping track of the current index, to determine which voice to play next. With that approach, we'd lose the ability to call `noteRelease` with a MIDI value, and the ability to adjust the velocity based off of how many voices are active at that time...@jvntf, curious to get your insight on this idea?
