### ISSUE TITLE
Explore Continuous Integration options

### ISSUE THREAD

**Issue by JunShern** [processing/p5.js-sound#267]
I was trying to use the [p5.js random()](https://p5js.org/reference/#/p5/random) function to sample randomly from an array. Using `random([1,2,3])` in the online editor works fine, but using the p5.js-sound code, it throws an error. Upon inspection, it turns out that the [current version of random()](https://github.com/processing/p5.js-sound/blob/master/lib/p5.js#L27267) is an older version which does not support sampling from arrays.

This is simply a matter of syncing up the libraries with the latest code. So my question is, what is the procedure for updating our `lib/` folder with the latest library files?

**Comment by therewasaguy** [comment]
Great question. So far, we've updated the `lib/` when needed, if you just want to do that for now.

It'd be great to have a webhook hit some service that creates a PR to the p5.sound repo every time a new version of p5.js is released, and vice versa.

**Comment by therewasaguy** [comment]
Another option is to remove the `lib` and use p5.js from the CDN in all our local examples

**Comment by JunShern** [comment]
Hmm I haven't used webhooks before, but looking at [the GitHub tutorial](https://developer.github.com/webhooks/configuring/) it appears we need a server to listen for the hook and make the pull request accordingly. Does Processing have any such backend servers we could use?

Regarding the CDN, I feel like it would be best to maintain local files just so that users can still work without an active internet connection.

In the meantime, I'll go ahead and update the files now.

**Comment by therewasaguy** [comment]
p5 uses Travis CI for continuous integration. That might be a good place to start, because it provides a free managed service for open source projects. Though it seems focused on building, testing, and deploying...I don't know to what extent we can customize webhooks to submit PR's for us. It is worth looking into what's possible and utilizing Travis CI for, at the very least

- run tests on PR's
- lint PR's
- keep our gh-pages branch in sync with master (assuming we'll continue to build off of the examples)

**Comment by montoyamoraga** [comment]
since p5.js doesn't use Travis CI anymore, and so much has changed since 2018,
i am closing this issue for now ~
