### ISSUE TITLE
callback in addCue is called multiple times per cue time

### ISSUE THREAD

**Issue by rjpgt** [processing/p5.js-sound#443]
p5 version: 1.0.0
p5.sound version: 0.3.12
Firefox 74.0.1, Ubuntu 19.10

The `callback` in `addCue(time, callback, [value])` is being called multiple times per cue time. The `value` remains the same until the next cue time.

Is this the desired behaviour?

I would have expected the `callback` to be called only once per cue time.

To see this, go to to the [online example](https://p5js.org/reference/#/p5.SoundFile/addCue) for `addCue` and modify it slightly as follows:
```
let mySound;
let numCalls;
function preload() {
  mySound = loadSound('assets/Damscray_DancingTiger.mp3');
}

function setup() {
  let cnv = createCanvas(100, 100);
  cnv.mousePressed(canvasPressed);
  background(220);
  text('tap to play', 10, 20);
  
  // schedule calls to changeText
  mySound.addCue(0, changeText, "hello" );
  mySound.addCue(0.5, changeText, "hello," );
  mySound.addCue(1, changeText, "hello, p5!");
  mySound.addCue(1.5, changeText, "hello, p5!!");
  mySound.addCue(2, changeText, "hello, p5!!!!!");

  mySound.onended(() => console.log(numCalls));
}

function changeText(val) {
  background(220);
  text(val, 10, 20);
  ++numCalls;
}

function canvasPressed() {
  numCalls = 0;
  mySound.play();
}
```

I get numCalls to be 44 or 45 and not 5. In Google Chrome it is 600 or so.

**Comment by endurance21** [comment]
@rjpgt thanks for the insight view of the API !!
i just figured out the problem!
it is due to the precision prolem of numbers !
infact playbackTime of the sound in p5.sound  is the  decimal value and the schedules times provided ( eg 0, 0.5, 1 here ) , 
may be not equal to the playback at a given time , because javascript provides diff threads for AUDIO processing  and normal js {  if i am not wrong :p  @therewasaguy  ? } and that's why the playbackTime and callbackTime may be not equal And also it will depend on machine and browser performing the rendering of js !!!


![Selection_078](https://user-images.githubusercontent.com/43696525/79693032-063b4e80-8286-11ea-81ec-20ed8847b5c2.png)
``
as we can see the current implementation of checking if playbackTime and callBackTime  are equla , is not that accurate and provides  some extra calling 0f CALLBACK functions ! :p
 ``

As a part of a experiment on my machine i observerd that 
there is 173 calls for one cue point !! ;)
and if my maths is good :p , then you willl get 
173 * 5 = 865 approx or may be less ( as it depends on machine ) callback calls!!!!

**Comment by rjpgt** [comment]
I haven't gone through the code. But using the fact that these extra calls are being made with the same `val` I was able to get around the issue.
But the code you have quoted does not show the use of any equality tests of `playbackTime` and `callbackTime`. Only inequalities are being used. Equality tests can't be used anyway for floating point numbers.

**Comment by endurance21** [comment]
@rjpgt  
by saying equality , i meant that  how much close these  two numbers  are .  sorry for that  
:sweat_smile:

does'nt matter now , **because I have fixed the issue**  :smiley:



!! 
have a look at  my sketch , given below 
point to be noted : 
> 1. i have modified the p5.js-sound library in my local codebase so i have used the p5.js-sound.min.js in the sketch as you can see !

 > 2. i have added my audio  in the sketch , please check it with your own song !

> https://editor.p5js.org/endurance21/sketches/Y4PIYR5wY  

try to add as much cue as you want and test it , let me know if it is not working in any case !!

**Comment by rjpgt** [comment]
Good that you have fixed it. I had a look at the code( your modification actually) right now. The only essential difference I see is that instead of `~~this._prevUpdateTime` you have `this._prevUpdateTime` in the `if` condition. `~~` is a substitute for `Math.floor` I have now come to understand. Wasn't that the actual problem, rounding the previous callback time to an integer? This is just for my understanding.

**Comment by endurance21** [comment]
@rjpgt 
Actually two problems were there 😶
1. The playbackTime increase very slightly as the audio plays,  let's say if it is 1.02 next iteration it will be 1.0202735 and so on and rounding off them everytime makes them 1 so unless they reach 2 the condition will always be true for every value in the range of 1 to 2  and that's why extra calls were there.
2. this. _prevUpdateTime was  happen to be undefined for the playbackTime equal to zero or slightly more than that, because it was not then defined , however making
this. _prevUpdateTime = playbackTime || 0, ensures that if it is undefined make it 0

and that's how it happen to solve the problem!!!

Hope that helps 😁

**Comment by rjpgt** [comment]
ok, thanks.

**Comment by rjpgt** [comment]
Has your change been merged with p5.sound.js in the lib folder? When can I get p5.sound.js with your changes merged in?

**Comment by rjpgt** [comment]
Does p5.sound.js on github now have these changes merged in? Thanks.

**Comment by endurance21** [comment]
@rjpgt yes you can see it merged pr#449

**Comment by rjpgt** [comment]
Yes it is in the src folder. The p5.sound.js in the lib folder does not
have the changes i think. To build p5.sound.js from the new src files do I
have to run grunt? I am not familiar with the process that makes the final
p5.sound.js.

**Comment by endurance21** [comment]
First install all depencies
1.npm install
 Then build the library
2.grunt

And thats all, you ll fins the library in
Lib/ folder 🙃
