### ISSUE TITLE
P5.signal has been removed from codebase, deprecation warning suggestion

### ISSUE THREAD

**Issue by endurance21** [processing/p5.js-sound#581]
New release of p5.js-sound wont be supporting p5.Signal anymore, for existing users we must show a deprecation warning when they try to acess the method

**Comment by endurance21** [comment]
@montoyamoraga 
i was wondering , how usually we handle decpreactions in p5.js codbase ?

**Comment by montoyamoraga** [comment]
hi @endurance21 ~
i don't know how we have handled deprecations in the past,
if we haven't done it in the past, i wouldn't add this feature,
or maybe low hanging fruit would be using the Friendly Error System,
but i'm not familiar it ~
i would ask people who have done huge code refactors,
such as @outofambit @limzykenneth  :)

**Comment by limzykenneth** [comment]
I don't think we have deprecated any API before mainly because for a long time we just release them as breaking changes before 1.0.0.

I think we can do two things to deprecate a feature, first, as @montoyamoraga mentioned, is to use the FES to log a deprecation message in the console (or maybe even using console.log if we want minify versions to show deprecation message as well). Second, we can mark the API as deprecated in the documentation. Actual removal of support will probably be done only when the next major version is released, whenever that is, though you can note in the deprecation message and the documentation that the feature is no longer being maintained.

**Comment by endurance21** [comment]
I would like to go with 
` removing the documentation of p5.signal simply ` 
.
But many projects relying on this api is gonna break , I am bit sad about that ;)

**Comment by limzykenneth** [comment]
@endurance21 We can hide it from search and being listed on the main reference page certainly.

**Comment by outofambit** [comment]
I completely agree with @limzykenneth's proposal here! i would vote we use `console.log` over FES to make sure it appears for folks running the minified version of p5.

**Comment by endurance21** [comment]
Thank you @outofambit  @limzykenneth  @montoyamoraga 
For the discussion, I will go with console.log thing .

And could you guys please confirm , when exactly is new p5.js version is gonna role .
Like it would take a week or so for me to fix the stuff with p5.js-sound and to ship it with p5.js codebase .

A tentative date?
