### ISSUE TITLE
P5 + Nuxt

### ISSUE THREAD

**Issue by andresclua** [processing/p5.js-sound#687]
I'm trying to set up P5.js inside Nuxt but is not working.
I'm using Nuxt 2 & sometimes it's says "window not defined"

Tried cdn version or npm version, both doesnt work.

<img width="903" alt="index_vue_—_frontend" src="https://user-images.githubusercontent.com/612806/204100796-e6f003ae-a892-4a0a-9be0-4c59746fb5b7.png">

Any help on this is welcome!

**Comment by lf32** [comment]
Why did you comment the `src`?

**Comment by andresclua** [comment]
I try both options, import it and added as script, both are not working.

**Comment by davepagurek** [comment]
Is it trying to use serverside rendering? If so, that's probably the issue -- there's a similar problem in Nextjs where you can't import anything related to p5 directly since `window` won't be defined on the server when compiling pages.

You can try using dynamic imports instead:
```js
async mounted() {
  const p5 = await import('p5');
  new p5((sketch) => {
    sketch.setup = function() { /* ... */ };
    sketch.draw = function() { /* ... */ };
  })
}
```

See this stackoverflow question for more info: https://stackoverflow.com/questions/67824862/how-to-make-a-dynamic-import-in-nuxt

Anyway I'm going to close this issue for now since this isn't an issue with p5.sound, but feel free to ask for more help on the [p5 discord](https://discord.gg/SHQ8dH25r9) if anyone has had more direct experience using p5 with Nuxt.
