### ISSUE TITLE
No sound with Mozilla Firefox on Ubuntu/Linux

### ISSUE THREAD

**Issue by ezimuel** [processing/p5.js-sound#73]
This library does not work on Mozilla FireFox. I'm trying with FireFox 41.0.1 on Ubuntu 15.04, no sound at all. I tried also the online examples, for instance [this one](http://p5js.org/examples/examples/Sound__Note_Envelope.php).

**Comment by therewasaguy** [comment]
Hi @ezimuel, are you seeing any error messages in the console? I'm not seeing library-specific issues in FF 40.0.3 or 41.0.2. I'm testing on mac 10.10.5. I can't test on Ubuntu right now, but if anyone else can please chime in!

**Comment by ezimuel** [comment]
No, I don't have any error message in the console. I'm testing this online project: http://catodo.net/deobsolescentia/. On Chrome everything is ok. Maybe this is an issue of FireFox on Ubuntu :(

**Comment by therewasaguy** [comment]
Your project is working on Firefox and Chrome for me (and super cool!)

But if I have the mouse over the area where the photo is supposed to be before the photo has finished loading, I get an error:

`` Uncaught TypeError: Cannot read property 'loadPixels' of undefined  ``  ``   setup.js:55``

This is because loadImage happens asynchronously and it isn't guaranteed to have finished loading before the first draw() loop.

A couple options:
- you could move your ``loadImage`` to a ``preload`` function, which waits for everything to load before calling ``setup``
- On the first line of the draw loop, you could check to see that photo exists as part of that if statement

Please let me know if you still have issues with sound.

**Comment by ezimuel** [comment]
@therewasaguy I changed the `preload()` function to load the photo object with the first image.
Anyway, the sound is not working on FireFox. This should be an issue on Ubuntu/Linux only.
Thanks for your feedback!

**Comment by b2renger** [comment]
well I've tested with firefox 41.0 on ubuntu 15.04 (32bits) the project and the examples seem to work all right.

**Comment by ezimuel** [comment]
@b2renger so it's only a problem of my environment. I'll investigate with Mozilla. Thanks!
