### ISSUE TITLE
Missing error handling for loadSound()

### ISSUE THREAD

**Issue by bplmp** [processing/p5.js-sound#83]
The loadSound() function doesn't have an onerror() callback for error handling when loading files.

For a longer discussion on this topic: https://forum.processing.org/two/discussion/13569/catching-file-not-found-errors-with-loadsound

**Comment by therewasaguy** [comment]
Thanks for bringing this up! Working on it in [this branch](https://github.com/therewasaguy/p5.js-sound/tree/loadingcallbacks).

Unfortunately I don't think there is a way to prevent the browser from throwing a 404 error.

Also, the request doesn't treat 404 like an error - it's a response from a server. So it needs to be updated onreadystatechange. For more info, see this thread: http://stackoverflow.com/a/12915839/2994108. Since 404 is not treated like an error, I'm thinking to pass the errorCallback a custom Error object with a stack trace that points to the line in the sketch where the error occurred, and includes the url it tried to load.

Is there anything in particular you'd like to receive in the error-handling callback?

**Comment by bplmp** [comment]
Thanks for working on this!

I guess it wouldn't necessarily need to prevent the 404 error, but only not run the onload callback if there is a 404 error. The loadSound function could have 3 callbacks:

loadSound(path, [on load callback], [while loading callback], [on file not found callback]);

In this way the onload callback would not be executed if the file wasn't found.

**Comment by therewasaguy** [comment]
cool, this is added!

loadSound(path, [on load callback], [on file not found callback], [while loading callback]);

I experimented with a custom error object that may come in handy or may be overkill. But I thought it would be helpful to be able to figure out from the error what url failed to load (e.failedPath) and maybe do something based on that.

**Comment by bplmp** [comment]
Just tried it, works perfectly! Thanks, @therewasaguy !
