### ISSUE TITLE
amp() - don't cancel previously scheduled values

### ISSUE THREAD

**Issue by Joghurt72** [processing/p5.js-sound#84]
I had a problem with osc.amp(). See the forum entry:
https://forum.processing.org/two/discussion/13588/osc-amp-issue#latest

I'm on Mac OSX 10.9.5, using the latest p5js editor. Also checked it with Sublime 2 with the latest library.

**Comment by therewasaguy** [comment]
I responded on the forum. Controlling amplitude changes from events, rather than in the draw loop, solves the issue. But this brings up another issue: When you set amplitude to fade over time, it cancels any previously scheduled fades, so it fades to zero from the oscillator's default amplitude. I'm not sure if this is the desired behavior because in cases like these it can lead to confusion.
