### ISSUE TITLE
iOS - buzzing when p5sound is enabled

### ISSUE THREAD

**Issue by prayash** [processing/p5.js-sound#86]
Hello,

I'm currently writing a hybrid mobile app using Ionic framework and p5.js + p5sound.js. I'm trying to create a simple musical toy which has an oscillator generating some basic tones. Everything works fine with the audio, except when I plug in headphones there is a very loud buzzing coming through the app. It needs to be shut down and restarted to work properly through headphones, at which point when the headphones get ejected, the app gets corrupted and won't generate sound (with or without headphones) until the device is restarted. I've isolated the problem down and just the fact that I'm importing p5sound is causing the buzz to happen. Currently testing it out on iOS 9.1.

XCode 7.1 print this on the console everytime the headphones are plugged in/out:

```
ERROR:    [AVAudioSession Notify Thread] AVAudioSessionPortImpl.mm:49: ValidateRequiredFields: Unknown selected data source for Port iPhone Microphone (type: MicrophoneBuiltIn)
```

Could this be a problem with the WebAudio API itself? Or the fact that it's looking for mic input? 
Obviously none of this stuff works when I visit from mobile Safari/Chrome. When it's packaged as an app it works great. I'm very happy with the library minus this problem. Any ideas will be appreciated! Even if I have to dig into the Objective-C stuff to disable mic inputs or something which may be causing it.

I also tried removing all audio input stuff from the p5sound library.. no luck. :(

**Comment by therewasaguy** [comment]
Thanks for the bug report! I have tested p5.sound with Cordova Phonegap but not Ionic, and not since ios 9.1 - I'll try to take a look this week...

In the meantime, my first thought would have also been to try removing all the AudioIn stuff from the library. But, [googling that AVAudioSession error](http://stackoverflow.com/questions/21116216/avaudiosessionmanager-availableinputs-unknown-selected-data-source-for-port-iph), I'm not sure if it's related to the buzzing sound...

Do your headphones also have a microphone input? Like the apple earbuds? If you try with headphones that don't have a mic on them, is there still a buzz? 

If you plug in the headphones before any user interaction (before touching the screen), do you still hear the buzz? If so, I'd guess it has something to do with [this workaround](https://github.com/processing/p5.js-sound/blob/master/src/sndcore.js#L273) to start web audio on ios devices that need a user interaction before activating the Web Audio API's audiocontext.

**Comment by prayashthapa** [comment]
Thanks @therewasaguy, I tried with multiple headphones with/without interaction before plugging in and no luck. Also tried using this (https://www.npmjs.com/package/ios-safe-audio-context) and that didn't work either.

I did test it on an iPhone 5S and it seems to work perfectly fine. I was having buzzing problems on my iPhone 6S. Maybe some subtle change in Apple's new API or something. I also tried changing sample rates and such.. but it didn't seem to make a difference. :(

Maybe filling out a bug report to Apple is the main thing to do here?
